language: node_js

env:
  - HAPPY_TEST_TIMEOUT=60000

node_js:
  - stable
  - 4

install: npm install --ignore-scripts

script:
  - npm run lint
  - npm run test:coverage

after_success:
  - npm run coverage:ci

cache:
  directories:
    - node_modules
